# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
# yazelix v4
edit = [
  { run = '~/.config/zellij/yazi/open_file.sh $1', desc = "Open File in a new pane" },
]

# yazelix v3
# edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
