# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
# edit = [{ run = 'zellij run -- nu -e "hx $1"', desc = "Open File in a new pane" }]
# edit = [{ run = 'zellij run -- hx "$1"', desc = "Open File in a new pane" }]
